# Generated by Django 2.1.1 on 2020-10-11 13:31

from django.db import migrations, models
import django.db.models.deletion
import payments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engineers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(max_length=30, null=True)),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('order_number', models.CharField(default=payments.models.random_string, max_length=30)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='engineers.Engineer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='products.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=10)),
                ('receiver_number', models.CharField(max_length=15)),
                ('receiver_plus_number', models.CharField(max_length=15)),
                ('zip_code', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(max_length=30)),
                ('delivery_message', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='paymentproduct',
            name='receiver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.Receiver'),
        ),
    ]
