# Generated by Django 2.1.1 on 2020-10-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engineers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='engineers.Engineer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
