# Generated by Django 2.1.1 on 2020-10-11 13:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='engineer_photos')),
                ('affiliation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(default=datetime.time(0, 0))),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='engineers.Engineer')),
            ],
        ),
    ]
