# Generated by Django 2.1.1 on 2020-10-11 13:31

import django.core.validators
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('sale', models.FloatField()),
                ('price', models.PositiveIntegerField(blank=True, default=0)),
                ('manufacture', models.CharField(max_length=50)),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('product_image', models.ImageField(upload_to='product/product_image')),
                ('image_description', models.ImageField(upload_to='product/image_description')),
                ('model_code', models.CharField(default=products.models.model_code, max_length=12)),
            ],
        ),
    ]
